name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        MONGODB_URL_TEST: ${{ secrets.MONGODB_URL_TEST }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - run: npm test
